DROP TABLE IF EXISTS annotatedpeaks;
DROP TABLE IF EXISTS available_genomes;
CREATE TABLE annotatedpeaks (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	genome_id INTEGER NOT NULL REFERENCES available_genomes(id),
	name TEXT NOT NULL,
	gene TEXT NOT NULL,
	_100K_Upstream_Number_of_Peaks INTEGER,
	_50K_Upstream_Number_of_Peaks INTEGER,
	_25K_Upstream_Number_of_Peaks INTEGER,
	_10K_Upstream_Number_of_Peaks INTEGER,
	_5K_Upstream_Number_of_Peaks INTEGER,
	_Promoters_Number_of_Peaks INTEGER,
	_5Prime_UTR_Number_of_Peaks INTEGER,
	_Exons_Number_of_Peaks INTEGER,
	_Introns_Number_of_Peaks INTEGER,
	_3Prime_UTR_Number_of_Peaks INTEGER,
	_2_5K_Downstream_Number_of_Peaks INTEGER,
	_5K_Downstream_Number_of_Peaks INTEGER,
	_10K_Downstream_Number_of_Peaks INTEGER,
	_25K_Downstream_Number_of_Peaks INTEGER,
	_50K_Downstream_Number_of_Peaks INTEGER,
	_100K_Downstream_Number_of_Peaks INTEGER,
	_100K_Upstream_Peaks_Information TEXT,
	_50K_Upstream_Peaks_Information TEXT,
	_25K_Upstream_Peaks_Information TEXT,
	_10K_Upstream_Peaks_Information TEXT,
	_5K_Upstream_Peaks_Information TEXT,
	_Promoters_Peaks_Information TEXT,
	_5Prime_UTR_Peaks_Information TEXT,
	_Exons_Peaks_Information TEXT,
	_Introns_Peaks_Information TEXT,
	_3Prime_UTR_Peaks_Information TEXT,
	_2_5K_Downstream_Peaks_Information TEXT,
	_5K_Downstream_Peaks_Information TEXT,
	_10K_Downstream_Peaks_Information TEXT,
	_25K_Downstream_Peaks_Information TEXT,
	_50K_Downstream_Peaks_Information TEXT,
	_100K_Downstream_Peaks_Information TEXT,
	UNIQUE (name, gene) ON CONFLICT REPLACE
);

CREATE TABLE available_genomes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	genome TEXT NOT NULL,
	_100K_Upstream_Peaks_File TEXT NOT NULL,
	_50K_Upstream_Peaks_File TEXT NOT NULL,
	_25K_Upstream_Peaks_File TEXT NOT NULL,
	_10K_Upstream_Peaks_File TEXT NOT NULL,
	_5K_Upstream_Peaks_File TEXT NOT NULL,
	_Promoters_Peaks_File TEXT NOT NULL,
	_5Prime_UTR_Peaks_File TEXT NOT NULL,
	_Exons_Peaks_File TEXT NOT NULL,
	_Introns_Peaks_File TEXT NOT NULL,
	_3Prime_UTR_Peaks_File TEXT NOT NULL,
	_2_5K_Downstream_Peaks_File TEXT NOT NULL,
	_5K_Downstream_Peaks_File TEXT NOT NULL,
	_10K_Downstream_Peaks_File TEXT NOT NULL,
	_25K_Downstream_Peaks_File TEXT NOT NULL,
	_50K_Downstream_Peaks_File TEXT NOT NULL,
	_100K_Downstream_Peaks_File TEXT NOT NULL,
	UNIQUE (genome, _100K_Upstream_Peaks_File, _50K_Upstream_Peaks_File, _25K_Upstream_Peaks_File, _10K_Upstream_Peaks_File, _5K_Upstream_Peaks_File, _Promoters_Peaks_File, _5Prime_UTR_Peaks_File, _Exons_Peaks_File, _Introns_Peaks_File, _3Prime_UTR_Peaks_File, _2_5K_Downstream_Peaks_File, _5K_Downstream_Peaks_File, _10K_Downstream_Peaks_File, _25K_Downstream_Peaks_File, _50K_Downstream_Peaks_File, _100K_Downstream_Peaks_File) ON CONFLICT IGNORE
);
