CREATE TABLE humanannotatedpeaks (
	name TEXT NOT NULL,
	gene TEXT NOT NULL,
	Human_100K_Upstream_Number_of_Peaks INTEGER,
	Human_50K_Upstream_Number_of_Peaks INTEGER,
	Human_25K_Upstream_Number_of_Peaks INTEGER,
	Human_10K_Upstream_Number_of_Peaks INTEGER,
	Human_5K_Upstream_Number_of_Peaks INTEGER,
	Human_Promoters_Number_of_Peaks INTEGER,
	Human_5Prime_UTR_Number_of_Peaks INTEGER,
	Human_Exons_Number_of_Peaks INTEGER,
	Human_Introns_Number_of_Peaks INTEGER,
	Human_3Prime_UTR_Number_of_Peaks INTEGER,
	Human_2_5K_Downstream_Number_of_Peaks INTEGER,
	Human_5K_Downstream_Number_of_Peaks INTEGER,
	Human_10K_Downstream_Number_of_Peaks INTEGER,
	Human_25K_Downstream_Number_of_Peaks INTEGER,
	Human_50K_Downstream_Number_of_Peaks INTEGER,
	Human_100K_Downstream_Number_of_Peaks INTEGER,
	Human_100K_Upstream_Peaks_Information TEXT,
	Human_50K_Upstream_Peaks_Information TEXT,
	Human_25K_Upstream_Peaks_Information TEXT,
	Human_10K_Upstream_Peaks_Information TEXT,
	Human_5K_Upstream_Peaks_Information TEXT,
	Human_Promoters_Peaks_Information TEXT,
	Human_5Prime_UTR_Peaks_Information TEXT,
	Human_Exons_Peaks_Information TEXT,
	Human_Introns_Peaks_Information TEXT,
	Human_3Prime_UTR_Peaks_Information TEXT,
	Human_2_5K_Downstream_Peaks_Information TEXT,
	Human_5K_Downstream_Peaks_Information TEXT,
	Human_10K_Downstream_Peaks_Information TEXT,
	Human_25K_Downstream_Peaks_Information TEXT,
	Human_50K_Downstream_Peaks_Information TEXT,
	Human_100K_Downstream_Peaks_Information TEXT,
	PRIMARY KEY (name, gene)
);

CREATE TABLE mouseannotatedpeaks (
	name TEXT NOT NULL,
	gene TEXT NOT NULL,
	Mouse_100K_Upstream_Number_of_Peaks INTEGER,
	Mouse_50K_Upstream_Number_of_Peaks INTEGER,
	Mouse_25K_Upstream_Number_of_Peaks INTEGER,
	Mouse_10K_Upstream_Number_of_Peaks INTEGER,
	Mouse_5K_Upstream_Number_of_Peaks INTEGER,
	Mouse_Promoters_Number_of_Peaks INTEGER,
	Mouse_5Prime_UTR_Number_of_Peaks INTEGER,
	Mouse_Exons_Number_of_Peaks INTEGER,
	Mouse_Introns_Number_of_Peaks INTEGER,
	Mouse_3Prime_UTR_Number_of_Peaks INTEGER,
	Mouse_2_5K_Downstream_Number_of_Peaks INTEGER,
	Mouse_5K_Downstream_Number_of_Peaks INTEGER,
	Mouse_10K_Downstream_Number_of_Peaks INTEGER,
	Mouse_25K_Downstream_Number_of_Peaks INTEGER,
	Mouse_50K_Downstream_Number_of_Peaks INTEGER,
	Mouse_100K_Downstream_Number_of_Peaks INTEGER,
	Mouse_100K_Upstream_Peaks_Information TEXT,
	Mouse_50K_Upstream_Peaks_Information TEXT,
	Mouse_25K_Upstream_Peaks_Information TEXT,
	Mouse_10K_Upstream_Peaks_Information TEXT,
	Mouse_5K_Upstream_Peaks_Information TEXT,
	Mouse_Promoters_Peaks_Information TEXT,
	Mouse_5Prime_UTR_Peaks_Information TEXT,
	Mouse_Exons_Peaks_Information TEXT,
	Mouse_Introns_Peaks_Information TEXT,
	Mouse_3Prime_UTR_Peaks_Information TEXT,
	Mouse_2_5K_Downstream_Peaks_Information TEXT,
	Mouse_5K_Downstream_Peaks_Information TEXT,
	Mouse_10K_Downstream_Peaks_Information TEXT,
	Mouse_25K_Downstream_Peaks_Information TEXT,
	Mouse_50K_Downstream_Peaks_Information TEXT,
	Mouse_100K_Downstream_Peaks_Information TEXT,
	PRIMARY KEY (name, gene)
);
